---
# INSTALL RKE2 SERVER (MASTER)
- name: Install RKE2 Server on Master
  hosts: master
  become: yes

  tasks:
    - name: Install RKE2 server
      shell: curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh -

    - name: Enable and start RKE2 server
      systemd:
        name: rke2-server.service
        enabled: yes
        state: started

    - name: Wait for node-token to exist
      wait_for:
        path: /var/lib/rancher/rke2/server/node-token
        timeout: 120

    - name: Read node token
      slurp:
        src: /var/lib/rancher/rke2/server/node-token
      register: token_raw

    - name: Set master token fact
      set_fact:
        rke2_token: "{{ token_raw.content | b64decode | trim }}"

# INSTALL RKE2 AGENT (WORKER)
- name: Install RKE2 Agent on Worker
  hosts: worker
  become: yes

  tasks:
    - name: Install RKE2 agent
      shell: curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=agent sh -

    - name: Ensure rke2 config directory exists
      file:
        path: /etc/rancher/rke2
        state: directory
        mode: '0755'

    - name: Create agent config
      copy:
        dest: /etc/rancher/rke2/config.yaml
        content: |
          server: https://{{ groups['master'][0] }}:9345
          token: "{{ hostvars[groups['master'][0]].rke2_token }}"

    - name: Enable and start RKE2 agent
      systemd:
        name: rke2-agent.service
        enabled: yes
        state: started
